### ISSUE TITLE
a spelling mistake : --libary-type, which should be `--library-type`

### ISSUE THREAD

**Issue by gnilihzeux** [Kevinzjy/CIRIquant-cookbook#3]
As the title, I had suffered from this.

**Comment by Kevinzjy** [comment]
Fixed in [09614cc](https://github.com/Kevinzjy/CIRIquant/commit/09614cc259046ba9ca0c3afb153f96208c7d3df3), you can download the latest version from [master branch of CIRIquant](https://github.com/Kevinzjy/CIRIquant.git), or wait for the updated version on pypi.
